repository:
  name: agri-tool-mvp

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - Tests
      required_pull_request_reviews:
        required_approving_review_count: 1
