repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
  - repo: local
    hooks:
      - id: python-compile
        name: Python syntax check
        entry: python -m py_compile
        language: system
        files: \.py$
      - id: selenium-compliance
        name: Validate Selenium compliance
        entry: python validate_selenium_compliance.py
        language: system
        pass_filenames: false
