# Cloud Build configuration for SubsidyPilot Form Parser
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/subsidypilot-form-parser:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/subsidypilot-form-parser:latest',
      '.'
    ]

  # Push the Docker image to Container Registry  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/subsidypilot-form-parser:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/subsidypilot-form-parser:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'subsidypilot-form-parser',
      '--image', 'gcr.io/$PROJECT_ID/subsidypilot-form-parser:$COMMIT_SHA',
      '--region', 'europe-west1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '2Gi',
      '--cpu', '1',
      '--timeout', '300s',
      '--max-instances', '10',
      '--set-env-vars', 'NODE_ENV=production,SUPABASE_URL=https://gvfgvbztagafjykncwto.supabase.co',
      '--set-secrets', 'OPENAI_API_KEY=OPENAI_API_KEY:latest,SUPABASE_SERVICE_ROLE_KEY=SUPABASE_SERVICE_ROLE_KEY:latest'
    ]

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/subsidypilot-form-parser:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/subsidypilot-form-parser:latest'

# Build options
options:
  logging: LEGACY
  substitution_option: 'ALLOW_LOOSE'

# Build timeout
timeout: '1200s'