-- Add 4 new French subsidies from FranceAgriMer with correct data types
INSERT INTO public.subsidies_structured (
  title,
  description,
  agency,
  program,
  sector,
  funding_type,
  deadline,
  region,
  url,
  eligibility,
  application_method,
  funding_source,
  language,
  created_at
) VALUES 
(
  'Aide en faveur d''investissements réalisés pour la production de plantes à parfum, aromatiques et médicinales',
  'Cette décision définit les modalités d''intervention de FranceAgriMer en faveur des investissements matériels dans les exploitations agricoles produisant des Plantes à parfum, aromatiques et médicinales (PPAM). Cette aide est mise en œuvre sous couvert du régime cadre notifié N° SA 107520 (2023/N).',
  'FranceAgriMer',
  'Établissement national des produits de l''agriculture et de la mer',
  ARRAY['Plantes à parfum, aromatiques et médicinales'],
  'public',
  '2025-04-30',
  ARRAY['France métropolitaine'],
  'https://www.franceagrimer.fr/aides/aide-en-faveur-d-investissements-realises-pour-la-production-de-plantes-a-parfum-aromatiques-et-medicinales',
  'Exploitations agricoles de France métropolitaine actives dans la production primaire de plantes à parfum, aromatiques et médicinales (PPAM). Projets dont le montant des investissements éligibles est supérieur à 500 € HT. Maximum 20 000 € par demandeur sur 3 ans. Taux: 40% pour ≤15 000€, 20% pour 15 000-85 000€.',
  'Formulaire de demande via documents associés',
  'FranceAgriMer',
  'fr',
  NOW()
),
(
  'Aide au développement de navires et bateaux innovants améliorer la performance énergétique ou environnementale',
  'Mise en œuvre d''un programme d''aide aux projets d''investissements pour le développement de navires et bateaux innovants pour améliorer la performance énergétique ou environnementale.',
  'FranceAgriMer',
  'Plan de relance pêche et aquaculture',
  ARRAY['Pêche et aquaculture'],
  'public',
  '2021-04-30',
  ARRAY['France métropolitaine', 'Régions ultrapériphériques'],
  'https://www.franceagrimer.fr/aides/aide-au-developpement-de-navires-et-bateaux-innovants-ameliorer-la-performance-energetique-ou',
  'PME du secteur pêche et aquaculture, organisations de producteurs, associations d''organisations de producteurs, organisations interprofessionnelles, organismes de recherche et de diffusion des connaissances, organismes de droit public. Projets de navires prototypes/démonstrateurs innovants. Min 100k€, Max 2M€/projet, 4M€/bénéficiaire. Enveloppe: 15M€.',
  'Appel à projets - Formulaire en ligne',
  'FranceAgriMer',
  'fr',
  NOW()
),
(
  'Aide aux projets d''investissements GE de transformation et commercialisation et dans les ports',
  'Aide aux investissements dans les ports de pêche, les halles à marée et les sites de débarquement ainsi que dans le domaine de la transformation et de la commercialisation des produits de la pêche et de l''aquaculture par des grandes entreprises.',
  'FranceAgriMer',
  'Plan de relance pêche et aquaculture',
  ARRAY['Pêche et aquaculture'],
  'public',
  '2022-04-29',
  ARRAY['France', 'Outre-mer'],
  'https://www.franceagrimer.fr/aides/aide-aux-projets-dinvestissements-ge-de-transformation-et-commercialisation-et-dans-les-ports',
  'Grandes entreprises disposant d''un N° SIRET. Projets d''investissement dans les ports de pêche, halles à marée, sites de débarquement, ou transformation/commercialisation des produits de la pêche et aquaculture. Projet non commencé au moment du dépôt. Enveloppe: 28M€.',
  'Appel à projets - Formulaire en ligne via opérateur avec N° SIRET',
  'FranceAgriMer',
  'fr',
  NOW()
),
(
  'FEAMP - Appel à projets pour l''innovation - Mesures 47',
  'Le Fonds européen pour les affaires maritimes et la pêche (FEAMP) soutient l''innovation dans le secteur de l''aquaculture pour encourager une aquaculture durable sur le plan environnemental, efficace dans l''utilisation des ressources, innovante, compétitive et fondée sur les connaissances.',
  'FranceAgriMer',
  'Fonds européen pour les affaires maritimes et la pêche (FEAMP)',
  ARRAY['Pêche et aquaculture'],
  'public',
  '2019-05-31',
  ARRAY['France'],
  'https://www.franceagrimer.fr/aides/feamp-appel-projets-pour-linnovation-mesures-47',
  'Entreprises de la pêche et de l''aquaculture. Projets d''innovation technique et/ou organisationnelle, développement de nouvelles espèces, amélioration qualité/valorisation produits, nouveaux marchés, collaboration profession/recherche/développement. Financement européen FEAMP.',
  'Appel à projets avec cahier des charges',
  'Union européenne',
  'fr',
  NOW()
);