-- Add 4 new French subsidies from FranceAgriMer
INSERT INTO public.subsidies_structured (
  title,
  description,
  agency,
  program,
  sector,
  funding_type,
  deadline,
  amount,
  region,
  url,
  eligibility,
  application_method,
  contact_info,
  reference_code,
  status,
  created_at
) VALUES 
(
  'Aide en faveur d''investissements réalisés pour la production de plantes à parfum, aromatiques et médicinales',
  'Cette décision définit les modalités d''intervention de FranceAgriMer en faveur des investissements matériels dans les exploitations agricoles produisant des Plantes à parfum, aromatiques et médicinales (PPAM). Cette aide est mise en œuvre sous couvert du régime cadre notifié N° SA 107520 (2023/N).',
  'FranceAgriMer',
  'Établissement national des produits de l''agriculture et de la mer',
  'Plantes à parfum, aromatiques et médicinales',
  'public',
  '2025-04-30',
  'Maximum 20 000 € par demandeur sur une période de 3 ans consécutifs. Taux : 40% pour investissements ≤15 000€, 20% pour 15 000-85 000€',
  'France métropolitaine',
  'https://www.franceagrimer.fr/aides/aide-en-faveur-d-investissements-realises-pour-la-production-de-plantes-a-parfum-aromatiques-et-medicinales',
  'Exploitations agricoles de France métropolitaine actives dans la production primaire de plantes à parfum, aromatiques et médicinales (PPAM). Projets dont le montant des investissements éligibles est supérieur à 500 € HT.',
  'Formulaire de demande via documents associés',
  'Voir documents associés sur le site FranceAgriMer',
  'SA 107520 (2023/N)',
  'open',
  NOW()
),
(
  'Aide au développement de navires et bateaux innovants améliorer la performance énergétique ou environnementale',
  'Mise en œuvre d''un programme d''aide aux projets d''investissements pour le développement de navires et bateaux innovants pour améliorer la performance énergétique ou environnementale.',
  'FranceAgriMer',
  'Plan de relance pêche et aquaculture',
  'Pêche et aquaculture',
  'public',
  '2021-04-30',
  'Minimum 100 000 € - Maximum 2 M€ par projet (aide maximum 1 M€) - Maximum 4 M€ par bénéficiaire. Enveloppe totale : 15 M€',
  'France métropolitaine et régions ultrapériphériques',
  'https://www.franceagrimer.fr/aides/aide-au-developpement-de-navires-et-bateaux-innovants-ameliorer-la-performance-energetique-ou',
  'PME du secteur pêche et aquaculture, organisations de producteurs, associations d''organisations de producteurs, organisations interprofessionnelles, organismes de recherche et de diffusion des connaissances, organismes de droit public. Projets de navires prototypes/démonstrateurs innovants, conception de prototypes, équipements aquacoles, R&D.',
  'Appel à projets - Formulaire en ligne',
  'Planderelance-pechequa@franceagrimer.fr',
  'INTV-POP-010',
  'closed',
  NOW()
),
(
  'Aide aux projets d''investissements GE de transformation et commercialisation et dans les ports',
  'Aide aux investissements dans les ports de pêche, les halles à marée et les sites de débarquement ainsi que dans le domaine de la transformation et de la commercialisation des produits de la pêche et de l''aquaculture par des grandes entreprises.',
  'FranceAgriMer',
  'Plan de relance pêche et aquaculture',
  'Pêche et aquaculture',
  'public',
  '2022-04-29',
  'Enveloppe totale : 28 M€. Dépenses éligibles : investissements matériels/immatériels, prestations, frais de personnel, frais indirects (15% forfaitaire)',
  'France (incluant les outre-mer)',
  'https://www.franceagrimer.fr/aides/aide-aux-projets-dinvestissements-ge-de-transformation-et-commercialisation-et-dans-les-ports',
  'Grandes entreprises disposant d''un N° SIRET. Projets d''investissement dans les ports de pêche, halles à marée, sites de débarquement, ou transformation/commercialisation des produits de la pêche et aquaculture. Projet non commencé au moment du dépôt.',
  'Appel à projets - Formulaire en ligne via opérateur avec N° SIRET',
  'Planderelance-pechequa@franceagrimer.fr',
  'INTV-POP-2022-011',
  'closed',
  NOW()
),
(
  'FEAMP - Appel à projets pour l''innovation - Mesures 47',
  'Le Fonds européen pour les affaires maritimes et la pêche (FEAMP) soutient l''innovation dans le secteur de l''aquaculture pour encourager une aquaculture durable sur le plan environnemental, efficace dans l''utilisation des ressources, innovante, compétitive et fondée sur les connaissances.',
  'FranceAgriMer',
  'Fonds européen pour les affaires maritimes et la pêche (FEAMP)',
  'Pêche et aquaculture',
  'public',
  '2019-05-31',
  'Financement européen dans le cadre du FEAMP',
  'France',
  'https://www.franceagrimer.fr/aides/feamp-appel-projets-pour-linnovation-mesures-47',
  'Entreprises de la pêche et de l''aquaculture. Projets d''innovation technique et/ou organisationnelle, développement de nouvelles espèces, amélioration qualité/valorisation produits, nouveaux marchés, collaboration profession/recherche/développement.',
  'Appel à projets avec cahier des charges',
  'UP.FEAMP@franceagrimer.fr',
  'Mesure 47 - Règlement n°508/2014 article 47',
  'closed',
  NOW()
);