name: 🤖 AgriTool AI Processing Pipeline

on:
  workflow_dispatch:
    inputs:
      batch_size:
        description: 'AI batch size'
        required: false
        default: '25'
      max_records:
        description: 'Max records to process'
        required: false
        default: '100'
  workflow_run:
    workflows: ["🕷️ AgriTool Scraper Pipeline"]
    types: [completed]

jobs:
  ai-process:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
      - name: 📋 Checkout
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install Dependencies
        working-directory: AgriToolScraper-main
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🤖 Run AI Processing
        working-directory: AgriToolScraper-main
        env:
          SCRAPER_RAW_GPT_API: ${{ secrets.SCRAPER_RAW_GPT_API }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          python main.py \
            --mode ai-processing \
            --batch-size ${{ github.event.inputs.batch_size || '25' }} \
            --max-records ${{ github.event.inputs.max_records || '100' }}

      - name: 📊 Upload AI Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ai-results-${{ github.run_number }}
          path: |
            AgriToolScraper-main/ai_results.json
            AgriToolScraper-main/processing_log.txt