name: Deploy Supabase Edge Functions

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'supabase/functions/**'
      - '.github/workflows/deploy-edge-functions.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: supabase
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Supabase CLI
        run: npm install -g supabase

      - name: Authenticate with Supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase login "$SUPABASE_ACCESS_TOKEN"

      - name: Configure Supabase secrets
        env:
          SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SCRAPPER_RAW_GPT_API: ${{ secrets.SCRAPPER_RAW_GPT_API }}
          SCRAPER_RAW_GPT_API: ${{ secrets.SCRAPPER_RAW_GPT_API }}
        run: |
          supabase secrets set \
            SUPABASE_URL="$SUPABASE_URL" \
            NEXT_PUBLIC_SUPABASE_ANON_KEY="$NEXT_PUBLIC_SUPABASE_ANON_KEY" \
            SUPABASE_SERVICE_ROLE_KEY="$SUPABASE_SERVICE_ROLE_KEY" \
            OPENAI_API_KEY="$OPENAI_API_KEY" \
            SCRAPER_RAW_GPT_API="$SCRAPER_RAW_GPT_API"

      - name: Verify Supabase secrets
        run: |
          echo "Verifying secrets are set..."
          supabase secrets list

      - name: Deploy edge functions
        run: |
          for fn in classify-document extract-canonical-subsidy extract-document-data improve-subsidy-titles training-pipeline upload-farm-document ai-content-processor ai-test-single-page; do
            supabase functions deploy "$fn"
          done
