name: FranceAgriMer Subsidy Scraper

on:
  # Weekly schedule: Every Sunday at 01:00 UTC
  schedule:
    - cron: '0 1 * * 0'
  
  # Manual trigger for immediate execution
  workflow_dispatch:
    inputs:
      max_pages:
        description: 'Maximum pages to scrape (0 = unlimited)'
        required: false
        default: '0'
        type: string
      dry_run:
        description: 'Dry run mode (no database writes)'
        required: false
        default: 'false'
        type: choice
        options:
          - 'false'
          - 'true'

jobs:
  scrape-franceagrimer:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print runner/system context
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "RUNNER_OS: $RUNNER_OS"
          echo "HOSTNAME: $(hostname)"
          lsb_release -a || true
          env | sort
          df -h
          free -h
          which python3
          python3 --version
          pip --version

      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            chromium-browser \
            chromium-chromedriver \
            python3-pip \
            python3-venv
            
      - name: Install Python dependencies
        working-directory: ./AgriToolScraper-main
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Configure Chrome for headless operation
        run: |
          export CHROME_BIN=/usr/bin/chromium-browser
          export CHROMEDRIVER_BIN=/usr/bin/chromedriver
          
      - name: Set up environment variables
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> $GITHUB_ENV
          echo "SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" >> $GITHUB_ENV
          echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV
          echo "CHROMEDRIVER_BIN=/usr/bin/chromedriver" >> $GITHUB_ENV
          
      - name: 🔥 STEP 1 - SELENIUM 4+ COMPLIANCE CHECK
        working-directory: ./AgriToolScraper-main
        run: |
          set -xe
          echo "🔥 VERIFYING SELENIUM 4+ COMPLIANCE"
          python validate_selenium_compliance.py || (echo "❌ SELENIUM COMPLIANCE FAILED"; exit 1)
          echo "✅ SELENIUM 4+ COMPLIANCE VERIFIED"

      - name: 🔥 STEP 2 - CLEAR PYTHON CACHES  
        working-directory: ./AgriToolScraper-main
        run: |
          set -xe
          echo "🔥 CLEARING PYTHON CACHES"
          python clear_cache.py >clear_cache.log 2>&1 || (cat clear_cache.log; exit 1)
          echo "✅ PYTHON CACHES CLEARED"

      - name: 🔥 STEP 3 - DRIVER COMPLIANCE TEST
        working-directory: ./AgriToolScraper-main
        run: |
          set -xe
          echo "🔥 TESTING DRIVER INITIALIZATION"
          python test_driver_compliance.py >compliance_test.log 2>&1 || (cat compliance_test.log; exit 1)
          echo "✅ DRIVER COMPLIANCE VERIFIED"

      - name: 🔥 STEP 4 - FRANCEAGRIMER SCRAPER EXECUTION
        working-directory: ./AgriToolScraper-main
        run: |
          set -xe
          echo "🔥 STARTING FRANCEAGRIMER SUBSIDY SCRAPER"
          echo "📊 SCRAPER PARAMETERS:"
          echo "   Max Pages: ${{ github.event.inputs.max_pages || '0' }}"  
          echo "   Dry Run: ${{ github.event.inputs.dry_run || 'false' }}"
          echo ""
          
          python main.py \
            --url "https://www.franceagrimer.fr/Accompagner/Dispositifs-par-filiere/Aides-nationales" \
            --max_pages ${{ github.event.inputs.max_pages || '0' }} \
            --dry_run ${{ github.event.inputs.dry_run || 'false' }} \
            >scraper_main.log 2>&1 || (
              echo "❌ SCRAPER EXECUTION FAILED"
              echo "📋 SCRAPER LOG TAIL:"
              tail -n 100 scraper_main.log
              exit 1
            )
          
          echo "✅ FRANCEAGRIMER SCRAPER COMPLETED SUCCESSFULLY"
            
      - name: Upload scraper logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: scraper-logs-${{ github.run_number }}
          path: |
            AgriToolScraper-main/logs/
            AgriToolScraper-main/data/extracted/
            AgriToolScraper-main/data/raw_pages/
          retention-days: 30
          
      - name: Upload error screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: error-screenshots-${{ github.run_number }}
          path: |
            AgriToolScraper-main/data/extracted/error_*.png
          retention-days: 7
          
      - name: Print log tail on failure
        if: failure()
        run: |
          echo "===== LOG TAILS (last 50 lines each) ====="
          tail -n 50 AgriToolScraper-main/logs/* || true
          tail -n 50 AgriToolScraper-main/data/extracted/*log* || true
          tail -n 50 AgriToolScraper-main/*.log || true
          echo "===== Directory structure ====="
          find AgriToolScraper-main/

      - name: Dump all outputs and logs on failure
        if: failure()
        run: |
          echo "======= DIRECTORY STRUCTURE ======="
          find AgriToolScraper-main/
          echo "======= LOG DUMP ======="
          for f in AgriToolScraper-main/logs/*; do echo "=== $f ==="; tail -n 100 "$f" || true; done
          for f in AgriToolScraper-main/data/extracted/*; do echo "=== $f ==="; tail -n 100 "$f" || true; done
          for f in AgriToolScraper-main/*.log; do echo "=== $f ==="; tail -n 100 "$f" || true; done

      - name: ✅ SUCCESS NOTIFICATION
        if: success()
        run: |
          echo "🎉 FRANCEAGRIMER SCRAPER JOB COMPLETED SUCCESSFULLY"
          echo "="*60
          echo "📊 EXECUTION SUMMARY:"
          echo "   - Selenium 4+ Compliance: ✅ VERIFIED" 
          echo "   - Python Caches: ✅ CLEARED"
          echo "   - Driver Initialization: ✅ TESTED"
          echo "   - FranceAgriMer Scraping: ✅ COMPLETED"
          echo "="*60
          echo "📁 ARTIFACTS UPLOADED:"
          echo "   - Scraper logs and results"
          echo "   - Error screenshots (if any)"
          echo "   - Raw extracted data"
          echo "="*60
          echo "🚀 JOB STATUS: SUCCESS - READY FOR PRODUCTION"

      - name: ❌ FAILURE NOTIFICATION  
        if: failure()
        run: |
          echo "💥 FRANCEAGRIMER SCRAPER JOB FAILED"
          echo "="*60
          echo "❌ FAILURE ANALYSIS REQUIRED"
          echo "📋 CHECK THE FOLLOWING:"
          echo "   1. Selenium 4+ compliance violations"
          echo "   2. Driver initialization issues"
          echo "   3. Website structure changes"
          echo "   4. Network connectivity problems"
          echo "   5. Supabase credentials/permissions"
          echo "="*60
          echo "📁 DEBUG ARTIFACTS UPLOADED FOR ANALYSIS"
          echo "🔧 FIX ISSUES BEFORE RETRY"