name: FranceAgriMer Subsidy Scraper

on:
  schedule:
    - cron: '0 1 * * 0'
  workflow_dispatch:
    inputs:
      max_pages:
        description: 'Maximum pages to scrape (0 = unlimited)'
        required: false
        default: '0'
        type: string
      dry_run:
        description: 'Dry run mode (no database writes)'
        required: false
        default: 'false'
        type: choice
        options:
          - 'false'
          - 'true'
      force_purge:
        description: 'Force contamination purge (removes all non-FranceAgriMer artifacts)'
        required: false
        default: 'false'
        type: choice
        options:
          - 'false'
          - 'true'

jobs:
  scrape-franceagrimer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            chromium-browser \
            chromium-chromedriver \
            xvfb \
            python3-pip \
            python3-venv \
            file
      - name: Setup virtual display
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          sleep 3
        env:
          DISPLAY: :99

      - name: Debug Chrome/Chromedriver setup
        run: |
          echo "🔍 Chrome/Chromium debugging..."
          which chromium-browser || echo "chromium-browser not found"
          chromium-browser --version || echo "Cannot get Chromium version"
          which chromedriver || echo "chromedriver not found"
          chromedriver --version || echo "Cannot get chromedriver version"
          ls -l /usr/bin/chromedriver || true

      - name: Install Python dependencies
        working-directory: ./AgriToolScraper-main
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🔥 STEP 1 - SELENIUM 4+ COMPLIANCE VALIDATION
        working-directory: ./AgriToolScraper-main
        run: |
          python selenium_compliance_validator.py

      - name: 🔄 STEP 2 - CACHE CLEARING & CONDITIONAL PURGE
        working-directory: ./AgriToolScraper-main
        run: |
          python clear_cache.py
          if [ "${{ github.event.inputs.force_purge || 'false' }}" = "true" ]; then
            python purge_contamination.py
          fi

      - name: 🚗 STEP 3 - DRIVER COMPLIANCE TEST
        working-directory: ./AgriToolScraper-main
        env:
          DISPLAY: :99
        run: |
          python test_driver_compliance.py

      - name: 🇫🇷 STEP 4 - FRANCEAGRIMER SCRAPER EXECUTION
        working-directory: ./AgriToolScraper-main
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          DISPLAY: :99
          WDM_LOG: "1"
          WDM_LOG_LEVEL: "DEBUG"
        run: |
          if [ "${{ github.event.inputs.dry_run || 'false' }}" = "true" ]; then
            python main.py \
              --url "https://www.franceagrimer.fr/rechercher-une-aide" \
              --max-pages "${{ github.event.inputs.max_pages || '0' }}" \
              --dry-run
          else
            python main.py \
              --url "https://www.franceagrimer.fr/rechercher-une-aide" \
              --max-pages "${{ github.event.inputs.max_pages || '0' }}"
          fi

      - name: 📦 Upload logs and extracted data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: franceagrimer-scraper-output
          path: |
            AgriToolScraper-main/data/extracted/franceagrimer_*
            AgriToolScraper-main/data/logs/franceagrimer_*
            AgriToolScraper-main/job_execution_log.json
            AgriToolScraper-main/*.log
          retention-days: 30

      - name: Upload FranceAgriMer error screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: franceagrimer-errors-${{ github.run_number }}
          path: |
            AgriToolScraper-main/data/extracted/franceagrimer_screenshots_*
            AgriToolScraper-main/data/logs/franceagrimer_*error*.png
          retention-days: 7

      - name: Print debug information on failure
        if: failure()
        run: |
          echo "===== DEBUG INFORMATION ====="
          find AgriToolScraper-main/ -type f -name "*.log" || true
          find AgriToolScraper-main/data/ || true
          tail -n 50 AgriToolScraper-main/*.log || true
          tail -n 50 AgriToolScraper-main/data/logs/*.log || true
          tail -n 50 AgriToolScraper-main/data/extracted/*.log || true

      - name: ✅ SUCCESS NOTIFICATION
        if: success()
        run: |
          echo "🎉 FRANCEAGRIMER SCRAPER JOB COMPLETED SUCCESSFULLY"

      - name: ❌ FAILURE NOTIFICATION
        if: failure()
        run: |
          echo "💥 FRANCEAGRIMER SCRAPER JOB FAILED"
          echo "❌ FAILURE ANALYSIS REQUIRED"
          echo "   1. Selenium 4+ compliance violations"
          echo "   2. Driver initialization issues"
          echo "   3. Website structure changes"
          echo "   4. Network connectivity problems"
          echo "   5. Supabase credentials/permissions"
