name: AgriTool Scraper Pipeline

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Start URL (optional)'
        required: false
        default: 'https://www.afir.info/'
      max_pages:
        description: 'Max pages (optional)'
        required: false
        default: '2'
      dry_run:
        description: 'Dry run (true=no DB writes)'
        required: false
        default: 'true'
  schedule:
    - cron: '0 6 * * *' # runs daily at 6 AM UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: AgriToolScraper-main  # <--- change this if your folder name is different
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          python scraper_main.py --url "${{ github.event.inputs.target_url }}" --max-pages "${{ github.event.inputs.max_pages }}" ${{ github.event.inputs.dry_run == 'true' && '--dry-run' || '' }}

      - name: Upload logs and artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scraper-logs
          path: |
            scraper.log
            run_summary.json
