name: Phase D E2E Testing

on:
  workflow_dispatch:
    inputs:
      test_environment:
        description: 'Test environment'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production
      include_extended_tests:
        description: 'Run extended edge case tests'
        required: false
        default: 'true'
        type: choice
        options:
        - 'true'
        - 'false'
  schedule:
    - cron: "17 2 * * *"   # nightly 02:17 UTC
  # Gate deployments on harness success
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
        default: 'staging'

concurrency:
  group: phase-d-e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-harness:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      harness-result: ${{ steps.harness.outcome }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with: 
          deno-version: v1.x

      - name: Generate golden fixtures
        run: deno run --allow-read --allow-write --allow-net scripts/make_golden_fixtures.ts

      - name: Generate extended fixtures
        if: ${{ github.event.inputs.include_extended_tests != 'false' }}
        run: deno run --allow-read --allow-write --allow-net scripts/make_golden_fixtures_ext.ts

      - name: Run Phase D harness (core)
        id: harness
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          HARNESS_BUCKET: farm-documents
          HARNESS_USE_SERVICE_ROLE: "true"
        run: deno run --allow-read --allow-write --allow-net --allow-env scripts/phase_d_harness.ts

      - name: Run Phase D harness (extended)
        if: ${{ github.event.inputs.include_extended_tests != 'false' }}
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          HARNESS_BUCKET: farm-documents
          HARNESS_USE_SERVICE_ROLE: "true"
        run: deno run --allow-read --allow-write --allow-net --allow-env scripts/phase_d_harness_ext.ts

      - name: Upload test artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: phase-d-test-artifacts
          path: |
            fixtures/
            fixtures_ext/
            *.log
          retention-days: 7

      - name: Slack notify success
        if: success()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [ -n "$SLACK_WEBHOOK_URL" ]; then
            curl -X POST -H 'Content-type: application/json' \
              --data "{
                \"text\": \"🎉 Phase D harness: 21/21 passed\",
                \"blocks\": [
                  {
                    \"type\": \"section\",
                    \"text\": {
                      \"type\": \"mrkdwn\",
                      \"text\": \"*Phase D E2E Tests Passed* ✅\\n• Repository: $GITHUB_REPOSITORY\\n• Branch: $GITHUB_REF\\n• Commit: \`${GITHUB_SHA:0:8}\`\\n• All golden fixtures validated successfully\"
                    }
                  }
                ]
              }" \
              "$SLACK_WEBHOOK_URL"
          fi

      - name: Slack notify failure
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [ -n "$SLACK_WEBHOOK_URL" ]; then
            curl -X POST -H 'Content-type: application/json' \
              --data "{
                \"text\": \"🚨 Phase D harness FAILED\",
                \"blocks\": [
                  {
                    \"type\": \"section\",
                    \"text\": {
                      \"type\": \"mrkdwn\",
                      \"text\": \"*Phase D E2E Tests Failed* 🚨\\n• Repository: $GITHUB_REPOSITORY\\n• Branch: $GITHUB_REF\\n• Commit: \`${GITHUB_SHA:0:8}\`\\n• <$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID|View Logs>\"
                    }
                  },
                  {
                    \"type\": \"section\",
                    \"text\": {
                      \"type\": \"mrkdwn\",
                      \"text\": \"Phase D table extraction pipeline requires immediate attention. Check logs for detailed error information.\"
                    }
                  }
                ]
              }" \
              "$SLACK_WEBHOOK_URL"
          fi

  health-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: run-harness
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with: 
          deno-version: v1.x

      - name: Run Phase D validation script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: deno run --allow-net --allow-env --allow-read supabase/functions/extract-document-data/phase-d-test.ts

      - name: Create summary report
        run: |
          echo "## Phase D E2E Test Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Workflow**: ${{ github.workflow }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Trigger**: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment**: ${{ github.event.inputs.test_environment || 'staging' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Core Harness**: ${{ needs.run-harness.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Health Check**: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Timestamp**: $(date -u)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Ready for Production**: All systems validated" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Next Steps" >> $GITHUB_STEP_SUMMARY
          echo "1. Run deployment script: \`./scripts/deploy-phase-d.sh production\`" >> $GITHUB_STEP_SUMMARY
          echo "2. Monitor health queries for 24h" >> $GITHUB_STEP_SUMMARY
          echo "3. Scale backfill gradually" >> $GITHUB_STEP_SUMMARY